services:
  pokeapi:
    container_name: pokeapi
    "build": {
      "dockerfile": "Dockerfile"
    }
    ports:
      - "9000:9000"  # for PHP-FPM
      - "44857:44857"  # for Xdebug
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=44857
    volumes:
      - ./api:/var/www/html/
    restart: unless-stopped
    command: php artisan serve --host=0.0.0.0 --port=9000
    networks:
      - pokedex-network
networks:
  pokedex-network:
    driver: bridge